import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { resolve } from 'node:path'

export default defineConfig({
  plugins: [react(), tailwindcss()],
  base: '/',
  build: {
    rollupOptions: {
      // Real static pages for every public route in both languages, so each URL
      // returns 200 with its own <title>/description/hreflang instead of a SPA
      // 404 redirect. Generated by scripts/gen-html-pages.mjs.
      input: Object.fromEntries(
        ['pl', 'en', 'de', 'es', 'fr', 'it', 'pt'].flatMap(l => {
          const dir = l === 'pl' ? '' : `${l}/`;
          const dl = l === 'pl' ? 'pobierz' : 'download';
          const li = l === 'pl' ? 'logowanie' : 'login';
          return [
            [`${l}-landing`,  resolve(__dirname, `${dir}index.html`)],
            [`${l}-download`, resolve(__dirname, `${dir}${dl}/index.html`)],
            [`${l}-login`,    resolve(__dirname, `${dir}${li}/index.html`)],
          ];
        }),
      ),

    },
  },
  define: {
    __BUILD_ID__: JSON.stringify(new Date().toISOString().slice(0, 16).replace('T', ' ')),
    // Monotonic build number injected by CI (github.run_number); 0 in local/dev.
    __APP_BUILD__: JSON.stringify(Number(process.env.VITE_APP_BUILD ?? 0)),
  },
})
